const $ = id => document.getElementById(id);
const DAY = 1440;
const colors = ['#0a9d9c','#f1b43b','#8d6bd4','#3e94cc','#d87079','#5da76b'];
const defaults = [
  {id:'ac',name:'Aire acondicionado',kind:'ac',watts:953,source:'Nominal · placa',enabled:true},
  {id:'lights',name:'Iluminación · 2 lámparas',kind:'lights',watts:36,source:'Nominal · 18 W c/u',enabled:true},
  {id:'tv',name:'Televisor · 32 pulgadas',kind:'tv',watts:56,source:'Supuesto provisional',enabled:true}
];
let extras=[];
try { const saved=JSON.parse(localStorage.getItem('habita-devices')||'[]'); if(Array.isArray(saved)) extras=saved.filter(x=>x&&typeof x.name==='string'&&Number.isFinite(x.watts)&&x.watts>0&&x.watts<=5000).slice(0,12); } catch {}
let devices=[...defaults,...extras];
let overrides={};
let minute=7*60+30, day=1, speed=2, paused=false, model=null, aiBase='';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmt=n=>Math.round(n).toLocaleString('es-CO');
const hour=m=>m/60;
const timeLabel=m=>`${String(Math.floor((m%DAY)/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
function occupancy(m){const h=hour(m);return +(h>=6.7&&h<8.2||h>=12.1&&h<13.2||h>=18&&h<23.8||h<6.4);}
function schedule(d,m){const h=hour(m);if(d.kind==='ac')return (h>=12&&h<15.5||h>=19&&h<23.7)&&Math.sin(m/42)>-0.15;if(d.kind==='lights')return h>=18.3&&h<23.3||h>=5.8&&h<6.7;if(d.kind==='tv')return h>=19.2&&h<22.5;return false;}
function on(d,m){return overrides[d.id]===undefined?schedule(d,m):overrides[d.id];}
function watt(d,m){if(!d.enabled||!on(d,m))return 0;if(d.kind==='ac')return Math.round(d.watts*(.82+.13*Math.sin(m/17)**2));if(d.kind==='tv')return Math.round(d.watts*(.89+.09*Math.sin(m/13)**2));return d.watts;}
function total(m){return devices.reduce((n,d)=>n+watt(d,m),0);}
function ambient(m){const h=hour(m),ac=on(devices[0],m);return {t:clamp(27.3+1.75*Math.sin((h-8)/24*2*Math.PI)-(ac?1.65:0)+.18*Math.sin(m/47),22,31),rh:clamp(65+8*Math.sin((h+3)/24*2*Math.PI)+(ac?-5:0),35,90)};}
function probability(m,a){if(!model)return null;const h=hour(m),x=[1,occupancy(m),Math.sin(2*Math.PI*h/24),Math.cos(2*Math.PI*h/24),0,(a.t-27)/5,(a.rh-70)/20,+on(devices[0],m)];const z=x.reduce((s,v,i)=>s+v*model.coefficients[i],0);return 1/(1+Math.exp(-z));}
function points(values,w,h,pad=2){const min=Math.min(...values),max=Math.max(...values),span=Math.max(1,max-min);return values.map((v,i)=>`${(pad+i*(w-2*pad)/(values.length-1)).toFixed(1)},${(h-pad-(v-min)/span*(h-2*pad)).toFixed(1)}`).join(' ');}
function spark(id,fn,color){const vals=Array.from({length:24},(_,i)=>fn((minute-23*10+i*10+DAY)%DAY));$(id).innerHTML=`<polyline fill="none" stroke="${color}" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" points="${points(vals,120,28)}"/>`;}
function icon(kind){return ({ac:'▱',lights:'☼',tv:'▣'})[kind]||'ϟ';}
function saveExtras(){try{localStorage.setItem('habita-devices',JSON.stringify(devices.filter(d=>!['ac','lights','tv'].includes(d.id))));}catch{}}
function renderDevices(){const host=$('devices');host.replaceChildren();devices.forEach((d,i)=>{const card=document.createElement('article');card.className='device';const top=document.createElement('div');top.className='device-top';const glyph=document.createElement('span');glyph.className='device-icon';glyph.textContent=icon(d.kind);const toggle=document.createElement('button');toggle.type='button';toggle.className='switch'+(on(d,minute)?' on':'');toggle.setAttribute('role','switch');toggle.setAttribute('aria-checked',String(on(d,minute)));toggle.setAttribute('aria-label',`${d.name}: cambiar estado simulado`);toggle.addEventListener('click',()=>{overrides[d.id]=!on(d,minute);render();});top.append(glyph,toggle);const title=document.createElement('h3');title.textContent=d.name;const sub=document.createElement('div');sub.className='device-sub';sub.textContent=d.source;const foot=document.createElement('div');foot.className='device-foot';const val=document.createElement('strong');val.textContent=`${fmt(watt(d,minute))} W`;const note=document.createElement('small');note.textContent=on(d,minute)?'Encendido · simulado':'Apagado · simulado';foot.append(val,note);card.append(top,title,sub,foot);if(!['ac','lights','tv'].includes(d.id)){const remove=document.createElement('button');remove.className='device-remove';remove.type='button';remove.textContent='Eliminar equipo';remove.addEventListener('click',()=>{devices=devices.filter(x=>x.id!==d.id);delete overrides[d.id];saveExtras();render();});card.append(remove);}host.append(card);});}
function renderBreakdown(){const host=$('breakdown');host.replaceChildren();const max=Math.max(1,...devices.map(d=>watt(d,minute)));devices.forEach((d,i)=>{const wrap=document.createElement('div');const row=document.createElement('div');row.className='break-line';const name=document.createElement('span');const swatch=document.createElement('i');swatch.className='swatch';swatch.style.background=colors[i%colors.length];name.append(swatch,document.createTextNode(d.name));const amount=document.createElement('strong');amount.textContent=`${fmt(watt(d,minute))} W`;row.append(name,amount);const meter=document.createElement('div');meter.className='meter';const fill=document.createElement('i');fill.style.background=colors[i%colors.length];fill.style.width=`${watt(d,minute)/max*100}%`;meter.append(fill);wrap.append(row,meter);host.append(wrap);});$('sum').textContent=`${fmt(total(minute))} W`;}
function renderChart(){const svg=$('chart'),samples=Array.from({length:145},(_,i)=>total(i*10)),max=Math.max(1000,...samples)*1.08,left=43,right=704,top=15,bottom=211;const x=i=>left+i/(samples.length-1)*(right-left),y=p=>bottom-p/max*(bottom-top);const line=samples.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(' ');const current=x(minute/10),energy=samples.slice(0,-1).reduce((s,v)=>s+v/6/1000,0);svg.innerHTML=`<defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#28b9b0" stop-opacity=".26"/><stop offset="1" stop-color="#28b9b0" stop-opacity=".02"/></linearGradient></defs>${[0,.25,.5,.75,1].map(f=>`<line x1="${left}" x2="${right}" y1="${y(max*f)}" y2="${y(max*f)}" stroke="#e6eff1"/><text x="1" y="${y(max*f)+4}" fill="#8297a0" font-size="11">${(max*f/1000).toFixed(1)}</text>`).join('')}<path d="${line} L${right} ${bottom} L${left} ${bottom} Z" fill="url(#area)"/><path d="${line}" fill="none" stroke="#099d9b" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><line x1="${current}" x2="${current}" y1="${top}" y2="${bottom}" stroke="#215c70" stroke-dasharray="5 5"/><circle cx="${current}" cy="${y(total(minute))}" r="5" fill="#0b7885" stroke="white" stroke-width="2"/>`;$('daily-energy').textContent=`${energy.toFixed(2).replace('.',',')} kWh/día`;}
function renderPrediction(a){const p=probability(minute,a);if(p===null)return;$('prob').textContent=`${Math.round(p*100)} %`;$('progress').style.width=`${p*100}%`;const likely=p>=model.threshold;$('advice').textContent=likely?'El modelo estima mayor probabilidad de ocupación. Mantén el confort y revisa el consumo antes de cambiar el aire.':'El modelo estima menor probabilidad de ocupación. Verifica si hay personas antes de considerar apagar algún equipo.';const t=model.test;$('evidence').textContent=`Modelo entrenado con datos sintéticos. En prueba, exactitud ${(t.accuracy_model*100).toFixed(1)} % frente a ${(t.accuracy_baseline*100).toFixed(1)} % de una regla simple; Brier ${t.brier_model.toFixed(3)} frente a ${t.brier_baseline.toFixed(3)}. La regla obtuvo más aciertos. No existe evidencia de ahorro real ni autorización para controlar el aire con esta predicción.`;}
function render(){const a=ambient(minute);$('time').textContent=timeLabel(minute);$('day').textContent=`Día simulado ${day}`;$('rate').textContent=`1 s = ${speed} min`;$('temp').textContent=`${a.t.toFixed(1).replace('.',',')} °C`;$('humidity').textContent=`${Math.round(a.rh)} %`;$('occupancy').textContent=`${occupancy(minute)} ${occupancy(minute)===1?'persona':'personas'}`;$('power').textContent=`${fmt(total(minute))} W`;spark('spark-temp',m=>ambient(m).t,'#0ca994');spark('spark-humidity',m=>ambient(m).rh,'#2987cc');spark('spark-occupancy',occupancy,'#36ab65');spark('spark-power',total,'#8465c6');renderDevices();renderBreakdown();renderChart();renderPrediction(a);}
function appendMessage(text,who){const p=document.createElement('p');p.className=`bubble ${who}`;p.textContent=text;$('messages').append(p);$('messages').scrollTop=$('messages').scrollHeight;}
function localAnswer(q){const s=q.toLocaleLowerCase('es');const a=ambient(minute);if(/consum|potencia|gasta|equipo|energ[ií]a/.test(s)){const top=[...devices].sort((x,y)=>watt(y,minute)-watt(x,minute))[0];return `Ahora la potencia total estimada es ${fmt(total(minute))} W. ${top&&watt(top,minute)>0?`El mayor aporte es ${top.name}, con ${fmt(watt(top,minute))} W simulados.`:'Todos los equipos están apagados en la simulación.'} No es una medición real.`;}if(/temperatura|humedad|ambiente|calor/.test(s))return `En esta escena simulada hay ${a.t.toFixed(1).replace('.',',')} °C y ${Math.round(a.rh)} % de humedad relativa. Son valores generados, aún no llegan del BME680.`;if(/ocupaci|persona|predic|modelo/.test(s)){const p=probability(minute,a);return p===null?'El modelo aún no termina de cargar.':`Hay ${occupancy(minute)} personas simuladas ahora. El modelo estima ${Math.round(p*100)} % de probabilidad de ocupación dentro de 30 minutos. Se entrenó solo con datos sintéticos.`;}return 'Puedo analizar temperatura, humedad, ocupación y consumo de este tablero simulado. Para conversar libremente con DeepSeek falta conectar el servidor privado; nunca pondremos la clave en GitHub Pages.';}
async function askAI(question){if(!aiBase)return localAnswer(question);try{const r=await fetch(`${aiBase.replace(/\/$/,'')}/api/chat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,context:{time:timeLabel(minute),temperature_c:+ambient(minute).t.toFixed(1),humidity_pct:Math.round(ambient(minute).rh),occupancy:occupancy(minute),power_w:total(minute),devices:devices.map(d=>({name:d.name,power_w:watt(d,minute)})),data_origin:'simulated'}})});if(!r.ok)throw Error('Servidor no disponible');const data=await r.json();return typeof data.answer==='string'?data.answer:localAnswer(question);}catch{return `${localAnswer(question)} El servidor de DeepSeek no respondió; esta es una respuesta local limitada.`;}}
$('pause').addEventListener('click',()=>{paused=!paused;$('pause').textContent=paused?'Reanudar':'Pausar';});$('speed').addEventListener('click',()=>{speed=speed===2?8:2;$('speed').textContent=speed===2?'Velocidad ×4':'Velocidad normal';render();});$('reset').addEventListener('click',()=>{minute=7*60+30;day=1;overrides={};render();});
const dialog=$('device-dialog');$('add').addEventListener('click',()=>dialog.showModal());$('close').addEventListener('click',()=>dialog.close());$('cancel').addEventListener('click',()=>dialog.close());$('device-form').addEventListener('submit',e=>{e.preventDefault();const name=$('new-name').value.trim(),watts=Number($('new-watts').value);if(!name||!Number.isFinite(watts)||watts<1||watts>5000||devices.length>=15)return;devices.push({id:`extra-${Date.now()}`,name,kind:'extra',watts,source:'Potencia supuesta',enabled:true});saveExtras();$('device-form').reset();dialog.close();render();});
$('chat-form').addEventListener('submit',async e=>{e.preventDefault();const input=$('question'),q=input.value.trim();if(!q)return;appendMessage(q,'user');input.value='';const button=$('chat-form').querySelector('button');button.disabled=true;button.textContent='Pensando…';appendMessage(await askAI(q),'bot');button.disabled=false;button.textContent='Enviar';});
fetch('model.json').then(r=>{if(!r.ok)throw Error('Modelo no disponible');return r.json();}).then(x=>{model=x;render();}).catch(()=>{$('advice').textContent='No se pudo cargar el modelo. La simulación continúa, pero la predicción está deshabilitada.';});
fetch('config.json').then(r=>r.ok?r.json():{}).then(x=>{if(x&&typeof x.apiBase==='string'&&/^https:\/\//.test(x.apiBase))aiBase=x.apiBase;$('ai-status').textContent=aiBase?'DeepSeek configurado':'Análisis local';}).catch(()=>{$('ai-status').textContent='Análisis local';});
render();setInterval(()=>{if(paused)return;minute+=speed;if(minute>=DAY){minute%=DAY;day++;}render();},1000);
